import{a as q,S as v,i as E}from"./assets/vendor-DXaqCXe3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const p="49334882-a9a3b11390859b17c4f434c49";console.log("API KEY:",p);const P="https://pixabay.com/api/";async function h(e,r,n){try{return(await q.get(P,{params:{key:p,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data.hits}catch(s){throw console.error("Request error:",s),s}}const f=document.querySelector(".gallery"),c=document.querySelector(".loader");let y;function O(){f.innerHTML=""}function w(e){if(!f){console.error("Gallery element not found!");return}const r=e.map(({webformatURL:n,largeImageURL:s,tags:t="No description",likes:o,views:l,comments:b,downloads:S})=>`
        <li class="gallery-item">
          <a href="${s}" class="gallery-link">
            <img src="${n}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes:</strong> ${o}</p>
            <p><strong>Views:</strong> ${l}</p>
            <p><strong>Comments:</strong> ${b}</p>
            <p><strong>Downloads:</strong> ${S}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),y?y.refresh():y=new v(".gallery a")}function L(){c&&(c.style.display="block")}function m(){setTimeout(()=>{c&&(c.style.display="none",console.log("Loader hidden"))},500)}console.log(c);function a(e){E.error({title:"Error",message:e})}const $=document.querySelector(".form"),i=document.querySelector(".load-more");let d="",u=1;const g=15;document.addEventListener("DOMContentLoaded",()=>{m(),i.style.display="none"});$.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.elements["search-text"].value.trim();if(!r){a("Enter search query");return}r!==d&&(d=r,u=1,O()),L(),i.style.display="none";try{const n=await h(d,u,g);n.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(w(n),i.style.display="block")}catch{a("Something went wrong. Please try again!")}finally{m()}});i.addEventListener("click",async()=>{u+=1,L();try{const e=await h(d,u,g);e.length===0?(i.style.display="none",a("We're sorry, but you've reached the end of search results.")):(w(e),I(),e.length<g&&(i.style.display="none",a("We're sorry, but you've reached the end of search results.")))}catch{a("Something went wrong. Please try again!")}finally{m()}});function I(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
